In [1]:
import numpy as np

In [2]:
H = [[0, -1, 0, 0], [-1, 0, -1, 0], [0, -1, 0, -1], [0, 0, -1, 0]]

evals, evecs = np.linalg.eig(H) 

In [3]:
evals

array([-1.61803399, -0.61803399,  1.61803399,  0.61803399])

In [4]:
evecs[:, 0]

array([0.37174803, 0.60150096, 0.60150096, 0.37174803])

In [5]:
evecs[:, 1]

array([-0.60150096, -0.37174803,  0.37174803,  0.60150096])

In [7]:
evecs[:, 2]

array([-0.37174803,  0.60150096, -0.60150096,  0.37174803])

In [8]:
evecs[:, 3]

array([ 0.60150096, -0.37174803, -0.37174803,  0.60150096])