In [7]:
import numpy as np
from functions import *
from classes import *

In [8]:
length_x = 4
length_y = 1
dimension = length_x * length_y
n_elec_up = 2
n_elec_dn = 3
delta_tau = 0.5
t = 1

In [9]:
K1, evals, evecs = non_interacting_fermi_hubbard_ed(length_x, length_y, t, use_pbc=False)
K2 = hubbard_kinetic_2d_matrix(length_x, length_y, t, use_pbc=False)
wave_function = slaterWaveFunction2Spin(dimension, n_elec_up, n_elec_dn)
wave_function.wave_function_initialization(up_sates=evecs, down_states=evecs)
propagator = imaginaryTimePropagator(K1, delta_tau)
wave_function = propagator.apply_propagator(wave_function)

In [10]:
wave_function.wave_function_up

array([[ 0.83483433, -0.81929574],
       [ 1.35079031, -0.50635261],
       [ 1.35079031,  0.50635261],
       [ 0.83483433,  0.81929574]])

In [11]:
wave_function.wave_function_down

array([[ 0.83483433, -0.81929574, -0.16553776],
       [ 1.35079031, -0.50635261,  0.26784572],
       [ 1.35079031,  0.50635261, -0.26784572],
       [ 0.83483433,  0.81929574,  0.16553776]])

In [12]:
propagator.propagator

array([[1.13031811, 0.54298909, 0.13298816, 0.0216271 ],
       [0.54298909, 1.26330627, 0.56461618, 0.13298816],
       [0.13298816, 0.56461618, 1.26330627, 0.54298909],
       [0.0216271 , 0.13298816, 0.54298909, 1.13031811]])

In [18]:
propagator.one_body_operator_matrix * delta_tau

array([[ 0. , -0.5,  0. ,  0. ],
       [-0.5,  0. , -0.5,  0. ],
       [ 0. , -0.5,  0. , -0.5],
       [ 0. ,  0. , -0.5,  0. ]])

In [19]:
expm(propagator.one_body_operator_matrix * delta_tau)

array([[ 1.13031811, -0.54298909,  0.13298816, -0.0216271 ],
       [-0.54298909,  1.26330627, -0.56461618,  0.13298816],
       [ 0.13298816, -0.56461618,  1.26330627, -0.54298909],
       [-0.0216271 ,  0.13298816, -0.54298909,  1.13031811]])

In [13]:
np.array_equal(K1, K2)

True