In [1]:
import sys
import os
from pprint import pprint

sys.path.append(os.path.dirname(os.getcwd()))
# from src.core import * # type: ignore
from src.hamiltonians import *
from src.lattices import *
from src.propagators import *
from src.states import *
from src.walkers import *

In [ ]:
lat = Chain(4)
ham = HubbardSystem(lattice=lat)
state = SlaterDeterminantTwoSpinState(ham, n_electrons_up=2, n_electrons_down=2, dtype=np.float64)

In [3]:
print(state.phi_up)
print()
print(state.phi_down)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [4]:
state.initialize("non-interacting")

print(state.phi_up)
print()
print(state.phi_down)

[[ 0.5        -0.70506666 -0.05367498]
 [ 0.5         0.05367498 -0.70506666]
 [ 0.5         0.70506666  0.05367498]
 [ 0.5        -0.05367498  0.70506666]]

[[ 0.5        -0.70506666]
 [ 0.5         0.05367498]
 [ 0.5         0.70506666]
 [ 0.5        -0.05367498]]


In [5]:
walkers = np.array([Walker(state)])

In [6]:
print(walkers[0].get_phi_up())
print(walkers[0].get_phi_down())

[[ 0.5        -0.70506666 -0.05367498]
 [ 0.5         0.05367498 -0.70506666]
 [ 0.5         0.70506666  0.05367498]
 [ 0.5        -0.05367498  0.70506666]]
[[ 0.5        -0.70506666]
 [ 0.5         0.05367498]
 [ 0.5         0.70506666]
 [ 0.5        -0.05367498]]


In [11]:
walkers[0].orthogonalize()

In [12]:
print(walkers[0].get_phi_up())
print(walkers[0].get_phi_down())

[[-0.5         0.70506666  0.05367498]
 [-0.5        -0.05367498  0.70506666]
 [-0.5        -0.70506666 -0.05367498]
 [-0.5         0.05367498 -0.70506666]]
[[-0.5         0.70506666]
 [-0.5        -0.05367498]
 [-0.5        -0.70506666]
 [-0.5         0.05367498]]


In [14]:
walkers[0].get_phi_up().shape[0]

4